const srv1 =
    { name: 'Server 1', ipAddress: '192.168.1.101', uptime: '99.9%',uptime90:[
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Down", 45, Math.floor(Math.random() * 9) + 2],
    ["Degraded", 5, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Down", 30, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Degraded", 25, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Down", 45, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Down", 45, Math.floor(Math.random() * 9) + 2],
    ["Degraded", 5, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Down", 30, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Degraded", 25, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Down", 45, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Down", 45, Math.floor(Math.random() * 9) + 2],
    ["Degraded", 5, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Down", 30, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Degraded", 25, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["Degraded", 45, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
    ["No Downtime", 0, Math.floor(Math.random() * 9) + 2]
  ] }

    const srv2 =
    { name: 'Server 2', ipAddress: '192.168.1.102', uptime: '95.5%', uptime90:[
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["Degraded", 5, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["Down", 25, Math.floor(Math.random() * 9) + 2],
      ["Down", 60, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["Down", 45, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["Down", 45, Math.floor(Math.random() * 9) + 2],
      ["Degraded", 5, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["Down", 30, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["Degraded", 25, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["Degraded", 45, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2]] }

      const srv3=
    { name: 'Server 3', ipAddress: '192.168.1.103', uptime: '0%', uptime90:[
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2],
      ["No Downtime", 0, Math.floor(Math.random() * 9) + 2]] }
  
  export {srv1, srv2, srv3};